### ISSUE TITLE
-I option not useful?

### ISSUE THREAD

**Issue by leofiore** [alsaplayer/alsaplayer#13]
What is the purpose of the `-I` option? i tried to search in the source code and found only two references to [global_interface_script](https://github.com/alsaplayer/alsaplayer/search?utf8=%E2%9C%93&q=global_interface_script), which could be probably used but by who? And for what? No references on the man page, except for a short string, can be found. It probably requires a bit of documentation.

**Comment by domichel** [comment]
I don't know what this is. It appear here http://alsaplayer.cvs.sourceforge.net/viewvc/alsaplayer/alsaplayer/alsaplayer/AlsaPlayer.h?view=log with the 1.3 rev - Add patches for python interface (bugfixes, no dependancies of course).
Thanks to Evgeny Chukreev.

I am not sure, but I think  global_interface_script is just initialized with its args, that inside alsaplayer, and I don't think it can be accessed by external software like a python interface. Look like some very old work in progress that was never finished. So if I am right, that option can be removed, can you confirm this?

**Comment by leofiore** [comment]
I guess so. I hoped for some inner magical python/lua/whatever scripting module, but, oh well, who cares.
