### ISSUE TITLE
Build of master head fails with --no-undefined: multiple undefined references from interface/gtk2

### ISSUE THREAD

**Issue by GvMariani** [alsaplayer/alsaplayer#18]
I'm trying to build alsaplayer from git master head for Rosa Linux 2014.1 x86_64.
Among various things, our build system always passes "--no-undefined" to the linker... and this kills the build of libgtk2_interface.la at the link stage  (see attached build log).
AFAICT there are at least 3 "similar" (i.e. involving under-linking) issues:
- the Makefile for interface/gtk2 needs to explicitly add a "-ldl" to the libraries needed to build libgtk2_interface;
- next, somehow the build of libgtk2_interface does not link to the already built libalsaplayer.la, so the linker fails to find symbols: e.g. "ap_strlcpy";
- finally, the build searches (and does not find them) for a lot of symbols coming from the app module
  (Playlist::_, AlsaSubscriber::_, CorePlayer::\* and more...), but this one is not yet built at the time the linker searches for it: so another bunch of undefined references... For this one I tried to manually change the build order, by placing both app and alsaplayer modules after libalsaplayer and before the interface one in both the Makefile.am and configure.ac files, but the build still failed with the same errors as before, so I guess there is also an under-linking problem on top of the wrong build order...

[BuildFailed.txt](https://github.com/alsaplayer/alsaplayer/files/430589/BuildFailed.txt)

**Comment by domichel** [comment]
Can You reproduce it with the current code?

**Comment by GvMariani** [comment]
Unfortunately, yes:
[BuildFailed.txt](https://github.com/alsaplayer/alsaplayer/files/14967114/BuildFailed.txt)

However we have an easy way to avoid using --no-undefined while building and this works around the errors.
So you can close this issue if you like it... but it would be better to find a proper fix, IMHO.

**Comment by domichel** [comment]
I re-checked it. It is your system that add -no-undefined, so I close it.

But You are right, it would be better to find a proper fix for that issue.
