### ISSUE TITLE
Playlist shuffle is not totally random

### ISSUE THREAD

**Issue by hermannschwaerzler** [alsaplayer/alsaplayer#19]
We noticed that when we use `--shuffle` the playlist is shuffled indeed but after a restart of alsaplayer, when we shuffle the playlist again it gets randomised to the very same list everytime we do this.

This is due to the fact that `random_shuffle()` is used in `app/Playlist.cpp` without first initialising the pseudo-random number generator (see http://stackoverflow.com/questions/13459953/random-shuffle-not-really-random).

I fixed this in my fork:
https://github.com/hermannschwaerzler/alsaplayer/commit/485f17c9766fdbbf84f3e9455b5556c2f3545e4a

I suggest to include this patch into this project as well...

Greetings
Hermann

**Comment by loafoe** [comment]
@hermannschwaerzler please create a pull request and I'll merge
