### ISSUE TITLE
alsaplayer crash FLAC 24bit

### ISSUE THREAD

**Issue by billhuey** [alsaplayer/alsaplayer#22]
I'm getting a crash with 24bit FLAC files on the latest Raspbian

**Comment by domichel** [comment]
We need more info. Which alsaplayer version? Can you reproduce it with the last git code?

**Comment by loafoe** [comment]
@billhuey can you send the FLAC which crashes the player? thx!

**Comment by domichel** [comment]
@billhuey I will close that bug. It You can reproduce it, please open a new bug with an audio file that cause that crash.
