### ISSUE TITLE
Does not play opus with either ".opus" or ".ogg" extension.

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [alsaplayer/alsaplayer#27]
Hi,

Built from latest sources on Ubuntu 22.04.1 LTS Jammy.

Everything else seems to be working apart from not playing Opus audio files with ".opus" extension. I tried renaming to ".ogg" but makes no difference. According libsndaudio page there is opus support
[01 - BT - Nocturnal Transmission.zip](https://github.com/alsaplayer/alsaplayer/files/9433618/01.-.BT.-.Nocturnal.Transmission.zip)
.

**Comment by Michael-Z-Freeman** [comment]
Got it. In "_/alsaplayer/input/sndfile/sndfile_engine.c_" add "_|| !strcasecmp(dot, "opus")_" after line 292.

**Comment by domichel** [comment]
Sorry for the delay and thank You for the good report and the fix. I will apply it later.
