### ISSUE TITLE
Please tag new upstream versions

### ISSUE THREAD

**Issue by tillea** [alsaplayer/alsaplayer#30]
Hi, 
your latest changelog entry says

     # This is for the 0.99.82 release.

Could you please add some release tag as a signal for distributions that some new version is released?
Thank you, Andreas.

**Comment by domichel** [comment]
I just done it. Thank You for the reminder, Dominique

**Comment by tillea** [comment]
Am Sun, Aug 25, 2024 at 08:05:15AM -0700 schrieb Dominique Michel:
> I just done it. Thank You for the reminder, Dominique

Thanks to you.  The quick response was extremely helpful, Andreas.
