### ISSUE TITLE
debian merge

### ISSUE THREAD

**Issue by piem** [alsaplayer/alsaplayer#6]
hi!

i finally updated the debian package to 0.99.81. see the changes here:

  http://anonscm.debian.org/gitweb/?p=collab-maint/alsaplayer.git;a=summary

it would be great to have a new release including the latest changes as well as the following patches: http://anonscm.debian.org/gitweb/?p=collab-maint/alsaplayer.git;a=tree;f=debian/patches;h=fd8d6f6dfbea15f8ae8c4516fdbc4c3a4aba9340;hb=HEAD

`10_uptodate_configure.dpatch` can be ignored, all the other ones could be merged.

thanks!
piem

**Comment by domichel** [comment]
Sorry for the delay, I will close it.

**@erikd** Another time, you can close bugs yourself when you want to, it should just work.
